
services:
  mongodb:
    image: mongo:6.0
    container_name: liverpool_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: liverpool_db
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express:latest
    container_name: liverpool_mongo_express
    ports:
      - "8091:8091"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb

volumes:
  mongo_data: