spring.application.name=GestionPedidosLiverpool
server.port=8090
#spring.data.mongodb.uri=mongodb://localhost:27017/liverpool_db
spring.data.mongodb.uri=mongodb+srv://giovannymex_db_user:Bachue-747@clustergiomongodb.kwq2tkm.mongodb.net/liverpool_db
